name: Deploy

on:
  push:
    branches: [develop, main]

jobs:

  prepare_variables_dev:
    name: Prepare deployment variables for development environment
    runs-on: ubuntu-latest
    outputs:
      stack_name: ${{ steps.set-vars.outputs.stack_name }}
      portainer_env_vars: ${{ steps.set-vars.outputs.portainer_env_vars }}
    steps:
      - name: Set deployment variables
        id: set-vars
        run: |
          echo "stack_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
          echo "portainer_env_vars={'DB_PASSWORD': '${{secrets.DB_PASSWORD}}', 'REDIS_PASSWORD': '${{secrets.REDIS_PASSWORD}}', 'NEXTCLOUD_DOMAIN': '${{vars.NEXTCLOUD_DOMAIN}}', 'CLOUDFLARE_TUNNEL_TOKEN': '${{secrets.CLOUDFLARE_TUNNEL_TOKEN}}'}" >> $GITHUB_OUTPUT
    if: github.ref == 'refs/heads/develop'

  deploy_development:
    name: Deploy to development Portainer
    uses: twentythree-ch/github-workflows/.github/workflows/deploy-to-portainer.yml@main
    with:
      stack_name: ${{ github.event.repository.name }}  # Uses repo name as stack name
      portainer_url: "https://portainer-dev.twentythree.ch"
      portainer_endpoint_id: "2"
      gh_username: "vansummeren"
      run_network_test: true
      environment: "development"
    secrets:
      portainer_token: ${{ secrets.PORTAINER_TOKEN }}
      netbird_setup_key: ${{ secrets.NETBIRD_SETUP_KEY }}
      gh_token: ${{ secrets.GH_PAT }}
      env_vars: ${{ needs.prepare_variables_dev.outputs.portainer_env_vars }}
    if: github.ref == 'refs/heads/develop'
    needs: prepare_variables_dev

  
  prepare_variables_prod:
    name: Prepare deployment variables for development environment
    runs-on: ubuntu-latest
    outputs:
      stack_name: ${{ steps.set-vars.outputs.stack_name }}
      portainer_env_vars: ${{ steps.set-vars.outputs.portainer_env_vars }}
    steps:
      - name: Set deployment variables
        id: set-vars
        run: |
          echo "stack_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
          echo "portainer_env_vars={'DB_PASSWORD': '${{secrets.DB_PASSWORD}}', 'REDIS_PASSWORD': '${{secrets.REDIS_PASSWORD}}', 'NEXTCLOUD_DOMAIN': '${{vars.NEXTCLOUD_DOMAIN}}', 'CLOUDFLARE_TUNNEL_TOKEN': '${{secrets.CLOUDFLARE_TUNNEL_TOKEN}}'}" >> $GITHUB_OUTPUT
    if: github.ref == 'refs/heads/main'

  deploy_production:
    name: Deploy to production Portainer
    uses: twentythree-ch/github-workflows/.github/workflows/deploy-to-portainer.yml@main
    with:
      stack_name: ${{ github.event.repository.name }}  # Uses repo name as stack name
      portainer_url: "https://portainer-dev.twentythree.ch"
      portainer_endpoint_id: "2"
      gh_username: "vansummeren"
      run_network_test: true
      environment: "production"
    secrets:
      portainer_token: ${{ secrets.PORTAINER_TOKEN }}
      netbird_setup_key: ${{ secrets.NETBIRD_SETUP_KEY }}
      gh_token: ${{ secrets.GH_PAT }}
      env_vars: ${{ needs.prepare_variables_prod.outputs.portainer_env_vars }}
    if: github.ref == 'refs/heads/main'
    needs: prepare_variables_prod